version: '3'
services:
  fastapi-app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: melodydbfinal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2002
    ports:
      - "5432:5432"
