apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: m3
        image: karthikeyan222/fastapi-sample:v3.0 
        ports:
        - containerPort: 80
        env:
          - name: POSTGRES_HOST
            value: postgres-service
        # Add other environment variables as needed
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      name: http
      port: 8000
      targetPort: 8000
  type: LoadBalancer
